#!/usr/bin/with-contenv bash


# permissions
chown abc:abc -R \
	/scripts

# copy all addition post processing scripts
if [[ -e /scripts/other_scripts ]]; then 
	#append to ScriptDir if not done already
	if ! grep -q "/scripts/other_scripts" /defaults/nzbget.conf; then
		sed -i \
			-e 	'\|^ScriptDir|s|$|;/scripts/other_scripts|' \
			/defaults/nzbget.conf
	fi								
	# permissions
	chown abc:abc -R \
		/scripts/other_scripts
fi