#!/usr/bin/with-contenv bash


# permissions
chown abc:abc -R \
	/scripts

# copy all addition post processing scripts
[[ -e /scripts ]] && \
	cp -rf /scripts/* /app/scripts
 

if [[ ! -e /app/scripts/nzbToMedia/.git ]]; then
	/usr/bin/git clone https://github.com/clinton-hall/nzbToMedia /app/scripts/nzbToMedia
else
	cd /app/scripts/nzbToMedia && /usr/bin/git pull
fi

# permissions
chown abc:abc -R \
	/app/scripts