#!/usr/bin/with-contenv bash


# permissions
chown abc:abc -R \
	/scripts

# copy all addition post processing scripts
[[ -e /scripts ]] && \
	cp -rf /scripts/* /app/scripts
 

[[ ! -e /app/scripts/nzbToMedia/.git ]] && \
	/usr/bin/git clone https://github.com/clinton-hall/nzbToMedia /app/scripts/nzbToMedia
