#!/usr/bin/with-contenv bash


# permissions
chown abc:abc -R \
	/scripts
 

if [[ ! -e /app/scripts/nzbToMedia/.git ]]; then
	/usr/bin/git clone https://github.com/clinton-hall/nzbToMedia -b ${NZBTOMEDIA_BRANCH} /app/scripts/nzbToMedia
else
	cd /app/scripts/nzbToMedia && /usr/bin/git pull && /usr/bin/git checkout ${NZBTOMEDIA_BRANCH} 
fi

# permissions
chown abc:abc -R \
	/app/scripts