#!/usr/bin/with-contenv bash


# permissions
chown abc:abc -R \
	/scripts
 

if [[ ! -e /scripts/nzbToMedia/.git ]]; then
	/usr/bin/git clone https://github.com/clinton-hall/nzbToMedia -b ${NZBTOMEDIA_BRANCH} /scripts/nzbToMedia
else
	cd /scripts/nzbToMedia && /usr/bin/git pull && /usr/bin/git checkout ${NZBTOMEDIA_BRANCH} 
fi

#append to ScriptDir if not done already
if ! grep -q "/scripts/nzbToMedia" /defaults/nzbget.conf; then
	sed -i \
		-e 	'\|^ScriptDir|s|$|;/scripts/nzbToMedia|' \
		/defaults/nzbget.conf
fi


# permissions
chown abc:abc -R \
	/scripts