#!/usr/bin/with-contenv bash


if [[ ! -e /scripts/MP4_Automator/.git ]]; then
	/usr/bin/git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git /scripts/MP4_Automator
else
	cd /scripts/MP4_Automator && /usr/bin/git pull 
fi

#append to ScriptDir if not done already
if ! grep -q "/scripts/MP4_Automator" /defaults/nzbget.conf; then
	sed -i \
		-e 	'\|^ScriptDir|s|$|;/scripts/MP4_Automator|' \
		/defaults/nzbget.conf
fi


# permissions
chown abc:abc -R \
	/app/scripts